---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.11'

inputs:
- name: ci-branch
- name: source
- name: pull-request-input

outputs:
- name: pull-request-output

run:
  path: ci-branch/ci/scripts/create-pull-request.sh

params:
  GITHUB_TOKEN: ''
  BASE_OWNER: ''
  BASE_BRANCH: ''
  HEAD_OWNER: ''
  HEAD_BRANCH: ''
  MESSAGE: ''
